#!/usr/bin/env bash
#
# The contents of this file are subject to the Apache 2.0 license you may not
# use this file except in compliance with the License.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
#
# Copyright 2017 DFT project (http://www.debianfirmwaretoolkit.org).
# All rights reserved. Use is subject to license terms.
#
#
# Contributors list :
#
#    William Bonnet     wllmbnnt@gmail.com, wbonnet@theitmakers.com
#
#

# -----------------------------------------------------------------------------
#
# @SBIT description short description
#
# @SBIT hint  -1   Wrong number of arguments. Should be 1. Please check args in your test file
# @SBIT hint   1   Process is not running
# @SBIT hint   2   Process is running, but number of instance is not as expected
# @SBIT hint   3   Process is running, but is in Zombie state
# @SBIT hint   4   Process is running, but is in Dead state
#
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
#
# Argument definition
#
#    count : 1
#    arg 1 : expected process name (binary name without full path)
#    arg 2 : expected number of process instance
#
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Beginning of test script
# -----------------------------------------------------------------------------

# Activate "fail fast". Stop on first error encountered.
# set -e

#
# Method used to setup the test environment. You should do any initialisation,
# temporary files or directories creation, serial configuration, or whatever you
# need to do... here
#
setup()
{
    # Check the number of arguments. Should be 1
    if [ ! "${ARG_COUNT}" == "2" ] ;
    then
      return -1
    fi

    # Went so far ? thus everything is ok...
    return 0
}

#
# Method executing the real test case. It is called after setup, and before
# teardown. In case of succes it should return 0. Otherwise it returns an error
# code that will be used as exit code for this script.
#
# You may define this error code as an hint in the meta section (beginning of
# this script) as a @SBIT hint. Hints are using two arguments. First is an index,
# which must have the same value as the exit code you return, and a string that
# will be printed by the sbit engine as an "hint" to the tester.
#
# Expect hint to be displayed like this "Error 3 occured. You should check this"
#
do_test()
{
  # Check if the pid exist
  PROCESS_COUNT=$(pidof ${EXPECTED_PROCESS} | wc -w)

  # Compare to first args
  if [ "${PROCESS_COUNT}" == "0" ] ;
  then
    return 1
  fi

  if [ ! "${PROCESS_COUNT}" == "${EXPECTED_COUNT}" ] ;
  then
    return 2
  fi

  # Check if the interface exist
  PROCESS_IDS=$(pidof ${EXPECTED_PROCESS})

  # Iterate the list of PIDs and search for the one matching arguments
  for PID in ${PROCESS_IDS} ;
  do
      MATCH=$(ps axo pid,stat | grep ${PID} | grep Z)
      if [ "${MATCH}" != "" ] ;
      then
        return 3
      fi

      MATCH=$(ps axo pid,stat | grep ${PID} | grep D)
      if [ "${MATCH}" != "" ] ;
      then
        return 4
      fi
  done

  # Main exit, no error detected, return 0
  return 0
}

#
# Method used to cleanup the test environment after the test has been executed.
# Test environment should be restored to the same state it was in before setup
# was executed
#
teardown()
{
    # Went so far ? thus everything is ok...
    return 0
}

# Store command line arguments
ARG_COUNT=$#
EXPECTED_PROCESS=$1
EXPECTED_COUNT=$2

# Call the setup method and check its return code is 0. Otherwise something went wrong
setup
ret_setup=$?
if [ ! ${ret_setup} == 0 ]; then exit ${ret_setup} ; fi

# Call the test method and stores its return code in order to use it as final exit code
do_test
ret_test=$?

# Call the teardown method and check its return code is 0. Otherwise something went wrong
teardown
ret_teardown=$?
if [ ! ${ret_teardown} == 0 ]; then exit ${ret_teardown} ; fi

# Main exit, no error detected, return 0
exit ${ret_test}
